name: CSV Data Protection

on:
  pull_request:
    paths:
      - 'data/*.csv'
  push:
    branches:
      - main
      - master
    paths:
      - 'data/*.csv'

jobs:
  check-csv-integrity:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history to compare with base branch
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
    
    - name: Check CSV integrity
      run: |
        python .github/scripts/check_csv_integrity.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_BASE_REF: ${{ github.base_ref }}
        GITHUB_HEAD_REF: ${{ github.head_ref }}
        GITHUB_REF: ${{ github.ref }}
